import { z } from "zod";

export const attempt = z.object({
  input: z.string(),
  timeUsed: z.number(),
});

export const task = z.object({
  id: z
    .string()
    .describe(
      "The id of the task in database, it is auto generated by the database, skip it"
    )
    .optional(),
  name: z.string().describe("A short description of what the task is about"),
  type: z
    .enum(["coding", "system", "behavior", "project"])
    .describe("The type of the task"),
  attempts: z.array(attempt).describe("The attempts of the task"),
  summary: z.string().describe("The AI summary of the task").optional(),
  comment: z.string().describe("User comment of the task").optional(),
  date: z.string().describe("The date of the task, in YYYY-MM-DD format"),
  status: z
    .enum(["ready", "in progress", "complete", "block", "fail"])
    .default("ready"),
});

export const progress = z.record(z.string(), z.array(task));

export const user = z.object({
  name: z.string(),
  email: z.string(),
  progress: progress,
});

export const typeOfTasksSummary = z
  .enum(["today", "week", "month"])
  .describe("The type of the tasks summary");

export const taskSummary = z.object({
  type: typeOfTasksSummary,
  date: z.string().describe("From YYYY-MM-DD to YYYY-MM-DD"),
  summary: z.string().describe("The summary of the tasks"),
  majorMilestones: z
    .string()
    .describe("The major milestones achieved for the month")
    .optional(),
  productivity: z.string().describe("The productivity of the month").optional(),
  accomplishments: z
    .string()
    .describe("The accomplishments of the month")
    .optional(),
  strategyPatterns: z
    .string()
    .describe("The strategy patterns for the month")
    .optional(),
  improvement: z
    .string()
    .describe("Anything need to improve on algorithm and data structure")
    .optional(),
  progress: z
    .array(
      z.object({
        type: z.enum(["coding", "system", "behavior", "project"]),
        count: z
          .number()
          .describe("The number of completed tasks of this type"),
      })
    )
    .describe("The summary of the tasks"),
});

export const taskSummaryArray = z.array(taskSummary);
